services:
  server-1:
    image: golang:alpine
    volumes:
      - ./backend:/home/backend
    # build:
    #   context: .
    #   dockerfile: backend-dev.Dockerfile
    ports:
      - "8081:8081"
    working_dir: /home/backend
    command: go run .

networks:
  go-react-backend:
    driver: overlay