services:
  admin:
    container_name: go-react-admin
    image: node:slim
    volumes:
      - ./admin:/home/admin
    ports:
      - "8082:8082"
    working_dir: /home/admin
    command: sh -c "npm install && npm run dev"
  
  client:
    container_name: go-react-client
    image: node:slim
    volumes:
      - ./client:/home/client
    ports:
      - "8080:8080"
    working_dir: /home/client
    command: sh -c "npm install && npm run dev"

  server-1:
    container_name: go-react-server
    image: golang:alpine
    volumes:
      - ./backend:/home/backend
    # build:
    #   context: .
    #   dockerfile: backend-dev.Dockerfile
    ports:
      - "8081:8081"
    working_dir: /home/backend
    command: go run .
